# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_screen', '0006_page_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='delay_in_sec',
            field=models.IntegerField(default=5, verbose_name='Delay in seconds'),
        ),
    ]
