# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-20 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_screen', '0008_page_is_slideshow_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoscreen',
            name='title',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='info_view/%Y/%m/%d', verbose_name='image file'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
        ),
    ]
